// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_app.tsx';
import * as $1 from './routes/api/hello.ts';
import * as $2 from './routes/api/ws.ts';
import * as $3 from './routes/index.tsx';
import * as $$0 from './islands/GameOfLifeBoard.tsx';

const manifest = {
	routes: {
		'./routes/_app.tsx': $0,
		'./routes/api/hello.ts': $1,
		'./routes/api/ws.ts': $2,
		'./routes/index.tsx': $3,
	},
	islands: {
		'./islands/GameOfLifeBoard.tsx': $$0,
	},
	baseUrl: import.meta.url,
};

export default manifest;
